server:
  port: 8091
  ssl:
    key-store: classpath:abmy.online.pfx
    key-store-password: h4rhvdvz405yf6
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.212.34:3306/lzh_db?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: lzh
    password: 114514
  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    username: homyit_123@qq.com
    password: bhukmvibspnbcjej

mybatis:
  mapper-locations: org/example/yinxin/cn/homyit/mapper/*.xml
upload:
  path: /home/answer/ui/images/
  reUrl:  https://img.abmy.online/images/
